export const SUBURBS_BY_STATE = {
  NSW: [
    "Abbotsford","Aberdeen","Abermain","Adaminaby","Adamstown","Adamstown Heights","Adelong","Adjungbilly","Albion Park","Albion Park Rail",
    "Albury","Aldavilla","Alfords Point","Allambie Heights","Allowah","Allworth","Alma","Alton Vale","Ambarvale","Anambah",
    "Annandale","Annangrove","Appin","Arcadia","Arcadia Vale","Ardlethan","Argenton","Ariah Park","Armidale","Arncliffe",
    "Arndell Park","Arrawarra","Arrawarra Headland","Artarmon","Ashbury","Ashcroft","Ashfield","Ashford","Asquith","Auburn",
    "Austinmer","Austral","Avalon Beach","Avoca Beach","Avondale","Axehead","Ayr","Balgowlah","Balgowlah Heights","Balgownie",
    "Balmain","Balmain East","Balmoral","Balcolyn","Balranald","Bangor","Banksia","Bankstown","Bankstown Aerodrome","Banora Point",
    "Bar Beach","Barangaroo","Baranoa","Barden Ridge","Bardwell Park","Bardwell Valley","Barooga","Bateau Bay","Bathurst","Batlow",
    "Beacon Hill","Beecroft","Beenleigh","Belfield","Belgrave","Bella Vista","Bellambi","Bellevue Hill","Belmont","Belmore",
    "Belrose","Bendalong","Bensville","Beresfield","Berowra","Berowra Heights","Berowra Waters","Berridale","Berrigan","Berrima",
    "Berry","Bexley","Bexley North","Biamble","Biggenden","Bilgola Beach","Bilgola Plateau","Bilpin","Binalong","Binda",
    "Binnaway","Birchgrove","Birrong","Blackalls Park","Blackett","Blackheath","Blacktown","Blair Athol","Blakehurst","Bland",
    "Blayney","Bligh Park","Blue Bay","Blue Haven","Bluewater","Boambee","Boambee East","Bodalla","Bolton Point","Bombala",
    "Bomaderry","Bomaderry","Bondi","Bondi Beach","Bondi Junction","Bonnyrigg","Bonnyrigg Heights","Bonnells Bay","Bonville","Booker Bay",
    "Boolaroo","Boorowa","Bossley Park","Botany","Bourke","Bow Bowing","Bowenfels","Bowral","Braidwood","Branxton",
    "Breakfast Point","Brewarrina","Brighton-Le-Sands","Broadmeadow","Broken Hill","Bronte","Brookvale","Brooklyn","Brunswick Heads","Bulli",
    "Bullio","Bungendore","Burraneer","Burrawang","Burwood","Burwood Heights","Busby","Buttaba","Buttai","Byron Bay",
    "Cabarita","Cabarita Beach","Cabramatta","Cabramatta West","Camellia","Camden","Camden Haven","Camden South","Cameron Park","Cammeray",
    "Camperdown","Campbelltown","Campsie","Canley Heights","Canley Vale","Canowindra","Canterbury","Caringbah","Caringbah South","Carlton",
    "Caroona","Carramar","Carringbah","Carrington","Carss Park","Casula","Castle Cove","Castle Hill","Castelereagh","Caves Beach",
    "Cecil Hills","Cessnock","Charcoal","Charlestown","Chatswood","Cheltenham","Chester Hill","Chifley","Chittaway Bay","Chittaway Point",
    "Chullora","Church Point","Circular Quay","Claymore","Clemton Park","Clontarf","Cloverdale","Coalcliff","Cobargo","Cobar",
    "Cobargo","Coffs Harbour","Collarenebri","Collaroy","Collaroy Plateau","Colyton","Como","Coogee","Concord","Concord West",
    "Constitution Hill","Cooma","Coolamon","Coolangatta","Coonabarabran","Coonamble","Cootamundra","Corrimal","Cowra","Cranebrook",
    "Cremorne","Cremorne Point","Cringila","Crows Nest","Croydon","Croydon Park","Crystal Creek","Culburra Beach","Cullen Bullen","Curl Curl",
    "Currans Hill","Daceyville","Darlinghurst","Darlington","Dapto","Davidson","Dee Why","Deniliquin","Denistone","Denistone East",
    "Denistone West","Dharruk","Dolls Point","Doonside","Double Bay","Doyalson","Drummoyne","Dubbo","Dudley","Dulwich Hill",
    "Dungog","Dunmore","Dural","Eagle Vale","Earlwood","East Albury","East Hills","East Maitland","East Ryde","Eastgardens",
    "Eastlakes","Eastwood","Edensor Park","Eden","Edmondson Park","Edensor Park","Eight Mile Plains","Elizabeth Bay","Emerton","Emu Heights",
    "Emu Plains","Engadine","Erina","Erskine Park","Erskineville","Ettalong Beach","Evans Head","Fairfield","Fairfield East","Fairfield Heights",
    "Fairfield West","Fairy Meadow","Fassifern","Faulconbridge","Figtree","Fingal Bay","Fitzroy Falls","Five Dock","Fletcher","Forbes",
    "Forest Hill","Forest Lodge","Forestville","Forster","Freemans Reach","Frenchs Forest","Freshwater","Galston","Georges Hall","Gillieston Heights",
    "Girards Hill","Girraween","Gladesville","Glenbrook","Glenfield","Glenmore Park","Glenning Valley","Glenorie","Glenwood","Glebe",
    "Gosford","Grafton","Granville","Green Valley","Greenacre","Greenfield Park","Greenway","Gregory Hills","Greystanes","Grenfell",
    "Guildford","Guildford West","Gymea","Gymea Bay","Gwynneville","Halekulani","Hamilton","Hamlyn Terrace","Hammondville","Harris Park",
    "Hazelbrook","Hebersham","Heathcote","Helensburgh","Hill Top","Hillsdale","Holroyd","Holsworthy","Homebush","Homebush West",
    "Hornsby","Hornsby Heights","Horsley Park","Hurstville","Illawong","Ingleburn","Ingleside","Innes Park","Inverell","Islington",
    "Jamisontown","Jannali","Jennings","Jesmond","Jindalee","Jordan Springs","Karabar","Kariong","Katoomba","Kearns",
    "Kellyville","Kellyville Ridge","Kembla Grange","Kemps Creek","Kensington","Kenthurst","Kingsford","Kings Cross","Kingsgrove","Kingswood",
    "Kincumber","Kiama","Kirrawee","Kirribilli","Kotara","Kogarah","Ku-ring-gai","Kurmond","Kurnell","Kurrajong",
    "Kyeemagh","Lakemba","Lane Cove","Lane Cove North","Lane Cove West","Lapstone","Lavington","Lawson","Leichhardt","Lemon Tree Passage",
    "Leppington","Leura","Lidcombe","Lilyfield","Lismore","Lismore Heights","Lithgow","Little Bay","Liverpool","Long Jetty",
    "Longueville","Lucknow","Lugarno","Lurnea","Macquarie Fields","Macquarie Links","Maianbar","Maitland","Malabar","Mangrove Mountain",
    "Manly","Manly Vale","Marrickville","Mascot","Marayong","Maryland","Matraville","Mays Hill","McCarthy Creek","McMahons Point",
    "Meadowbank","Medlow Bath","Menai","Merewether","Merewether Heights","Merriwa","Merrylands","Merrylands West","Metford","Millers Point",
    "Milperra","Milsons Point","Minchinbury","Miranda","Mittagong","Molong","Monterey","Moorebank","Morisset","Mortdale",
    "Mortlake","Moss Vale","Mosman","Mount Colah","Mount Druitt","Mount Keira","Mount Kuring-Gai","Mount Ousley","Mount Pleasant","Mount Victoria",
    "Mudgee","Mulgoa","Mullumbimby","Murwillumbah","Muswellbrook","Nabiac","Narara","Narellan","Narellan Vale","Narrabeen",
    "Narara","Narromine","Narwee","Neutral Bay","Newcastle","Newcastle West","New Lambton","New Lambton Heights","Newington","Newtown",
    "Nords Wharf","Norwest","North Albury","North Avoca","North Bondi","North Gosford","North Manly","North Parramatta","North Richmond","North Rocks",
    "North Ryde","North Strathfield","North Sydney","North Wahroonga","North Willoughby","North Wollongong","Nowra","Oatlands","Oatley","Old Toongabbie",
    "Orange","Oxley Park","Pagewood","Palm Beach","Panania","Parramatta","Peakhurst","Peakhurst Heights","Pelican","Pemulwuy",
    "Pendle Hill","Penrith","Pennant Hills","Penshurst","Phillip","Picnic Point","Picton","Plumpton","Point Clare","Point Frederick",
    "Point Piper","Port Kembla","Port Macquarie","Potts Point","Prairiewood","Prestons","Prospect","Punchbowl","Pymble","Pyrmont",
    "Quakers Hill","Queanbeyan","Raby","Randwick","Raymond Terrace","Red Hill","Redfern","Regents Park","Revesby","Rhodes",
    "Richmond","Riverstone","Riverview","Rockdale","Rosehill","Rosebery","Roseville","Roseville Chase","Rooty Hill","Rouse Hill",
    "Rozelle","Russell Lea","Rydalmere","Ryde","St Andrews","St Clair","St George","St Ives","St Ives Chase","St Johns Park",
    "St Leonards","St Marys","St Peters","Sandy Beach","Saratoga","Schofields","Seaforth","Sefton","Shellharbour","Silverdale",
    "Silverwater","Singleton","Smithfield","South Coogee","South Granville","South Hurstville","South Penrith","South Turramurra","Spring Farm","Springwood",
    "Strathfield","Strathfield South","Summer Hill","Sutherland","Swansea","Sydenham","Sydney","Sydney Olympic Park","Tamworth","Taree",
    "Taren Point","Tarrawanna","Telopea","Tempe","Terrigal","The Entrance","The Oaks","Thornleigh","Toongabbie","Toukley",
    "Tuggerah","Tuncurry","Turramurra","Tuross Head","Tweed Heads","Tweed Heads South","Ultimo","Umina Beach","Unanderra","Upper Lachlan",
    "Villawood","Vincentia","Voyager Point","Wahroonga","Waitara","Wakeley","Wamberal","Warrawee","Warrawong","Warwick Farm",
    "Warrimoo","Waratah","Waratah West","Waterfall","Waterloo","Watsons Bay","Waverley","Wentworth Falls","Wentworth Point","Werrington",
    "Werrington County","Werrington Downs","Westmead","West Pymble","West Ryde","Whalan","Wickham","Wiley Park","Willmot","Willoughby",
    "Winston Hills","Wolli Creek","Wollongong","Wollstonecraft","Woodville","Woolgoolga","Woollahra","Woolooware","Woolwich","Woy Woy",
    "Yagoona","Yamba","Yennora","Yowie Bay","Zetland","Abbotsford","Arndell Park","Avoca","Baerami","Baerami Creek","Ballina",
    "Ballimore","Bangalow","Bingara","Blacksmiths","Bogangar","Bolwarra","Bolwarra Heights","Bonnells Bay","Boolaroo","Booragul",
    "Cooranbong","Edgeworth","Cardiff","Cardiff Heights","Cardiff South","Cameron Park","Cessnock","Charlestown","Chinderah","Chirnside Park",
    "Clareville","Coastlands","Cockle Creek","Colongra","Coolongolook","Coopernook","Cooranbong","Crangan Bay","Doyalson North","Dudley",
    "Edgecombe","Eleebana","Empire Vale","Ettalong Beach","Fennell Bay","Fingal Head","Forresters Beach","Fountaindale","Freemans Waterhole","Gateshead",
    "Georgetown","Glendale","Gwandalan","Halekulani","Hamlyn Terrace","Kanwal","Koolewong","Lake Haven","Lake Munmorah","Lemon Tree Passage",
    "Lochinvar","Macksville","Maclean","Mannering Park","Maryland","Minmi","Morisset","Morisset Park","Mulbring","Nelsons Plains",
    "North Avoca","Northern Sydney","Noraville","Nords Wharf","Ourimbah","Paxton","Point Frederick","Rathmines","Redhead","San Remo",
    "Seahampton","Speers Point","Summer Hill Creek","Summerland Point","Swansea Heads","The Hill","Toukley","Tumbi Umbi","Vacy","Wadalba",
    "Warners Bay","Watanobbi","Windale","Wollstonecraft","Wongawilli","Woongarrah","Wyong","Wyongah","Yarramalong",
    "Casino","Kyogle","Lismore","South Grafton","Maclean","Iluka","Yamba","Woolgoolga","Moonee Beach","Coffs Harbour",
    "Sawtell","Toormina","Boambee","Urunga","Macksville","Nambucca Heads","Bowraville","Kempsey","South Kempsey","Frederickton",
    "Crescent Head","Port Macquarie","Lake Cathie","Laurieton","Camden Haven","Wauchope","Telegraph Point","Comboyne","Wingham",
    "Taree","Forster","Tuncurry","Nabiac","Bulahdelah","Hawks Nest","Tea Gardens","Nelson Bay","Salamander Bay","Shoal Bay",
    "Anna Bay","Soldiers Point","Corlette","Fingal Bay","Raymond Terrace","Maitland","Cessnock","Branxton","Kurri Kurri","Greta",
    "Abermain","Weston","Heddon Greta","Cliftleigh","Lochinvar","Rutherford","Telarah","Thornton","Woodberry","Beresfield",
    "Tarro","Sandgate","Hexham","Warabrook","Broadmeadow","Islington","Wickham","Carrington","Stockton","Waratah","Waratah West",
    "Georgetown","Adamstown","Adamstown Heights","New Lambton","New Lambton Heights","Hamilton","Hamilton South","Hamilton East","Hamilton North","Cooks Hill",
    "The Junction","Bar Beach","Merewether","Merewether Heights","Dudley","Garden Suburb","Glendale","Cardiff","Boolaroo","Warners Bay",
    "Speers Point","Windale","Eleebana","Macquarie Hills","Cameron Park","West Wallsend","Barnsley","Edgeworth","Fletcher","Minmi",
    "Maryland","Holmesville","Plattsburg","Killingworth","Cessnock","Kearsley","Millfield","Kitchener","Aberdare","Cessnock","Gillieston Heights",
    "Mulbring","Wollombi","Broke","Pokolbin","Lovedale","Rothbury","Maitland","Maitland Vale","Lochinvar","Whittingham",
    "Singleton","Jerrys Plains","Muswellbrook","Aberdeen","Scone","Merriwa","Quirindi","Werris Creek","Tamworth","Manilla",
    "Barraba","Narrabri","Moree","Walgett","Collarenebri","Mungindi","Bourke","Brewarrina","Walgett","Collarenebri",
    "Lightning Ridge","Coonamble","Gilgandra","Dunedoo","Mudgee","Gulgong","Rylstone","Kandos","Bathurst","Orange","Blayney",
    "Cowra","Grenfell","Forbes","Parkes","Peak Hill","Tullamore","Trundle","Condobolin","Lake Cargelligo","Hillston",
    "Griffith","Leeton","Narrandera","Wagga Wagga","Junee","Temora","Cootamundra","Young","Yass","Gundagai","Tumut",
    "Batlow","Adelong","Tumbarumba","Holbrook","Albury","Lavington","Wodonga","Culcairn","Henty","Jindera",
    "Deniliquin","Moulamein","Balranald","Hay","Hillston","Ivanhoe","Wilcannia","Broken Hill","Silverton","Menindee",
    "Wentworth","Dareton","Buronga","Gol Gol","Mildura","Cobar","Nyngan","Warren","Trangie","Narromine",
    "Dubbo","Wellington","Molong","Canowindra","Cowra","Goulburn","Crookwell","Taralga","Captains Flat","Braidwood",
    "Bungendore","Queanbeyan","Jerrabomberra","Googong","Michelago","Cooma","Nimmitabel","Bombala","Delegate","Eden",
    "Merimbula","Pambula","Tura Beach","Bega","Bermagui","Narooma","Moruya","Batemans Bay","Ulladulla","Milton",
    "Mollymook","Shoalhaven Heads","Nowra","Bomaderry","Huskisson","Vincentia","Kangaroo Valley","Moss Vale","Bowral","Mittagong",
    "Picton","Camden","Narellan","Campbelltown","Leumeah","Minto","Ingleburn","Macquarie Fields","Casula","Liverpool",
  ],

  VIC: [
    "Abbotsford","Aberfeldie","Aireys Inlet","Airport West","Albanvale","Albion","Alcona","Aldona","Alexandra","Alfredton",
    "Altona","Altona Meadows","Altona North","Anglesea","Anstey","Apollo Bay","Ararat","Arcadia","Ardeer","Armadale",
    "Armadale","Armstrong Creek","Arundel","Ascot Vale","Ashburton","Ashwood","Aspendale","Aspendale Gardens","Asquith","Attwood",
    "Avondale Heights","Bacchus Marsh","Bairnsdale","Balaclava","Ballan","Ballarat","Ballarat Central","Ballarat East","Ballarat North","Bangholme",
    "Bannockburn","Banyule","Baxter","Bayswater","Bayswater North","Beaconsfield","Beaconsfield Upper","Beaufort","Belgrave","Belgrave Heights",
    "Belgrave South","Belmont","Benalla","Bendigo","Berwick","Birchip","Blackburn","Blackburn North","Blackburn South","Black Rock",
    "Blackwood","Blairgowrie","Bonbeach","Boronia","Box Hill","Box Hill North","Box Hill South","Braeside","Brandon Park","Braybrook",
    "Brighton","Brighton East","Broadmeadows","Brookfield","Brunswick","Brunswick East","Brunswick West","Bulleen","Bundoora","Burwood",
    "Burwood East","Cairnlea","California Gully","Camberwell","Campbellfield","Canterbury","Carrum","Carrum Downs","Castlemaine","Caulfield",
    "Caulfield North","Caulfield South","Chadstone","Cheltenham","Chelsea","Chelsea Heights","Cheltenham","Chirnside Park","Clarinda","Clayton",
    "Clayton South","Clifton Hill","Clyde","Clyde North","Cobram","Coburg","Coburg North","Coldstream","Colac","Collingwood",
    "Como","Coolaroo","Craigieburn","Cranbourne","Cranbourne East","Cranbourne North","Cranbourne South","Cranbourne West","Cremorne","Croydon",
    "Croydon Hills","Croydon North","Dallas","Dandenong","Dandenong North","Dandenong South","Darley","Daw Park","Dawson Street","Daylesford",
    "Deepdene","Deer Park","Delahey","Derrimut","Diamond Creek","Dingley Village","Donvale","Doreen","Doveton","Dromana",
    "Drouin","Dunkeld","Eaglehawk","East Bentleigh","East Brighton","East Geelong","East Ivanhoe","East Malvern","East Melbourne","Echuca",
    "Edithvale","Eltham","Eltham North","Elwood","Emerald","Endeavour Hills","Epsom","Essendon","Essendon North","Essendon West",
    "Eumemmerring","Evandale","Fairfield","Fairhaven","Fawkner","Ferntree Gully","Ferny Creek","Fitzroy","Fitzroy North","Flemington",
    "Flinders","Flora Hill","Footscray","Forest Hill","Frankston","Frankston North","Frankston South","Fraser Rise","Gembrook","Geelong",
    "Geelong West","Gisborne","Gladstone Park","Glen Huntly","Glen Iris","Glen Waverley","Glengarry","Glenroy","Glenorchy","Glenside",
    "Goroke","Greensborough","Greenvale","Grovedale","Grovedale","Hadfield","Hallam","Hamilton","Hampton","Hampton East",
    "Hampton Park","Harkaway","Hawthorn","Hawthorn East","Healesville","Heathmont","Heatherton","Heidelberg","Heidelberg Heights","Heidelberg West",
    "Highett","Highton","Hillside","Hoppers Crossing","Horsham","Hughesdale","Huntly","Invermay Park","Irymple","Jacana",
    "Jan Juc","Kangaroo Flat","Kalorama","Keilor","Keilor Downs","Keilor East","Keilor Lodge","Kensington","Kentville","Kerang",
    "Kilsyth","Kilsyth South","Kings Park","Kingston","Knoxfield","Kooyong","Kyabram","Lakes Entrance","Langwarrin","Langwarrin South",
    "Latrobe Valley","Launching Place","Laverton","Lara","Leongatha","Leopold","Lilydale","Little River","Longwarry","Lorne",
    "Lower Templestowe","Lynbrook","Lyndhurst","Lysterfield","Lysterfield South","Macleod","Maddingley","Maidstone","Malvern","Malvern East",
    "Manifold Heights","Manor Lakes","Maribyrnong","Maryborough","McKinnon","Meadow Heights","Melton","Melton South","Melton West","Mentone",
    "Menzies Creek","Mernda","Mickleham","Middle Footscray","Mill Park","Millgrove","Moe","Molesey","Montmorency","Mont Albert",
    "Mont Albert North","Moonee Ponds","Moorabbin","Moorabbin Airport","Mooroolbark","Mordialloc","Morwell","Mornington","Mount Eliza","Mount Evelyn",
    "Mount Martha","Mount Waverley","Mulgrave","Murrumbeena","Narre Warren","Narre Warren North","Narre Warren South","Newport","Newtown","Niddrie",
    "Noble Park","Noble Park North","Norlane","North Geelong","North Melbourne","North Shore","North Warrandyte","Northcote","Notting Hill","Nunawading",
    "Oak Park","Oakleigh","Oakleigh East","Oakleigh South","Officer","Olinda","Orbost","Ormond","Pakenham","Pakenham South",
    "Parkdale","Parkville","Pascoe Vale","Pascoe Vale South","Patterson Lakes","Pearcedale","Pennyroyal","Point Cook","Prahran","Preston",
    "Red Hill","Reservoir","Research","Richmond","Ringwood","Ringwood East","Ringwood North","Ripponlea","Robinvale","Rockbank",
    "Rosanna","Rosebud","Rowville","Royal Park","Roxburgh Park","Seaford","Seaholme","Sebastopol","Selby","Sherbrooke",
    "Skye","Somers","Somerville","Sorrento","Southbank","South Melbourne","South Morang","South Yarra","Springvale","Springvale South",
    "St Albans","St Helena","St Kilda","St Kilda East","St Kilda Road Central","Strathdale","Strathfieldsaye","Strathmore","Strathmore Heights","Sunbury",
    "Sunshine","Sunshine North","Sunshine West","Surrey Hills","Swan Hill","Sydenham","Tarneit","Taylors Hill","Taylors Lakes","Tecoma",
    "Templestowe","Templestowe Lower","The Basin","The Patch","Thomastown","Thomson","Thornbury","Thornton","Toorak","Torquay",
    "Traralgon","Tremont","Truganina","Tullamarine","Tullalook","Tyabb","Upwey","Vermont","Vermont South","Viewbank",
    "Waurn Ponds","Wantirna","Wantirna South","Wandin North","Wandin Valley","Warrandyte","Warrandyte South","Warragul","Waterways","Watsonia",
    "Watsonia North","Waverley Gardens","Wendouree","Werribee","Werribee South","Westmeadows","Williams Landing","Williamstown","Williamstown North","Windsor",
    "Wollert","Wonga Park","Wonthaggi","Woodend","Wyndham Vale","Yallambie","Yarra Glen","Yarra Junction","Yarraville","Yering",
    "Abbotsford","Albert Park","Alphington","Armadale","Ascot Vale","Badger Creek","Balnarring","Balnarring Beach","Bangholme","Barongarook",
    "Barwon Heads","Bellarine","Bellfield","Bellfield","Bennettswood","Birchgrove","Black Rock","Blackburn Lake","Blind Bight","Boneo",
    "Bonbeach","Bonshaw","Boronia","Box Hill Central","Brighton Heights","Broken River","Buln Buln","Burnside","Burnside Heights","Calder Park",
    "Camberwell","Chadstone","Clifton Springs","Cockatoo","Coldstream","Coranderrk","Cranbourne North","Dalmore","Dandenong Ranges","Darraweit Guim",
    "Deep Lead","Delacombe","Devon Meadows","Diggers Rest","Doncaster","Doncaster East","Drummartin","Drysdale","Dunheved","East Ringwood",
    "Elaine","Eltham North","Emu Creek","Etham","Eumemmerring","Faraday","Fitzroy","Flinders","Garfield","Garfield North",
    "Gladysdale","Glen Waverley","Grovedale","Guinea Hills","Harkaway","Hopetoun Park","Humevale","Jacana","Jancourt","Kalorama",
    "Kallista","Kangaroo Ground","Kialla","Koo Wee Rup","Koondrook","Kurunjang","Langwarrin South","Laverton North","Loch","Longford",
    "Lucknow","Macedon","Maddingley","Mannerim","Mannings","Mantons Creek","Marong","Marysville","Mawson Lakes","McCrae",
    "Meeniyan","Merricks","Merricks North","Michelago","Mickleham","Millgrove","Mirboo North","Moriac","Mount Burnett","Mount Dandenong",
    "Mount Macedon","Myrtleford","Nagambie","Nangwarry","Neerim South","Nerrina","Noojee","Nowa Nowa","Nyora","Olinda",
    "Phillip Island","Pirron Yallock","Port Albert","Port Welshpool","Portarlington","Portsea","Pyalong","Redesdale","Research","Riddells Creek",
    "Romsey","Rosedale","Rye","Safety Beach","Scoresby","Selby","Settlers Hills","Shelter Island","Shoreham","Silverleaves",
    "St Arnaud","Stawell","Steeltown","Strath Creek","Stratford","Sunbury","Taggerty","Tallarook","Tatura","Taylors Lakes",
    "Toolangi","Tonimbuk","Tooradin","Toorourrong","Trafalgar","Tyabb","Upper Beaconsfield","Viewbank","Wallan","Wandin East",
    "Warrandyte South","Waterloo Bay","Wheelers Hill","Whittington","Whitfield","Whorouly","Wollert","Woodstock","Woori Yallock","Wurruk",
    "Yallourn","Yea","Yering","Yorgo","Hopetoun","Seymour","Euroa","Wangaratta","Benalla","Bright","Myrtleford","Rutherglen",
    "Corowa","Yarrawonga","Cobram","Nathalia","Numurkah","Tocumwal","Finley","Deniliquin","Swan Hill","Kerang","Mildura","Red Cliffs",
    "Ouyen","Hopetoun","Donald","St Arnaud","Maryborough","Dunolly","Avoca","Ararat","Stawell","Horsham","Dimboola",
    "Nhill","Warracknabeal","Wycheproof","Charlton","Wedderburn","Castlemaine","Kyneton","Woodend","Romsey","Lancefield",
  ],

  QLD: [
    "Acacia Ridge","Agnes Water","Airlie Beach","Albany Creek","Algester","Allenstown","Alligator Creek","Andergrove","Annandale","Anstead",
    "Arana Hills","Archerfield","Arundel","Ashgrove","Ashmore","Aspley","Ayr","Bald Hills","Balmoral","Banyo",
    "Bargara","Bardon","Bayview Heights","Bellbowrie","Belmont","Berrinba","Beenleigh","Belgian Gardens","Bethania","Biggera Waters",
    "Bilinga","Birkdale","Boondall","Boondall","Booval","Boronia Heights","Bowen","Bowen Hills","Bracken Ridge","Brassall",
    "Bribie Island","Brisbane","Brisbane City","Broadbeach","Broadbeach Waters","Brookfield","Browns Plains","Budamba","Buderim",
    "Bundaberg","Bundall","Bundamba","Bundamba","Burleigh Heads","Burleigh Waters","Burpengary","Burpengary East","Cabarita","Calamvale",
    "Caloundra","Caloundra West","Camp Hill","Cannon Hill","Cannonvale","Capalaba","Carseldine","Casuarina","Cawarral","Cedar Creek",
    "Chapel Hill","Charleville","Charters Towers","Chermside","Chermside West","Chinchilla","Clear Island Waters","Cleveland","Coffs Harbour",
    "Coochiemudlo Island","Coomera","Coorparoo","Coolangatta","Coolum Beach","Cotton Tree","Cranbrook","Currimundi","Dalby","Darra",
    "Deception Bay","Doolandella","Drayton","Drewvale","Dundowran","Eagleby","Eagle Farm","East Mackay","East Toowoomba","Edens Landing",
    "Eight Mile Plains","Eimeo","Elanora","Emerald","Emu Park","Enoggera","Everton Park","Farleigh","Fernvale","Ferny Grove",
    "Ferny Hills","Fig Tree Pocket","Flagstone","Forest Lake","Fortitude Valley","Gailes","Garbutt","Gaven","Gaythorne","Geebung",
    "Gladstone","Glass House Mountains","Golden Beach","Goodna","Gracemere","Graceville","Grange","Griffin","Gympie","Hendra",
    "Helensvale","Hermit Park","Herston","Highland Park","Holland Park","Holland Park West","Holmview","Home Hill","Hope Island","Hyde Park",
    "Indooroopilly","Innisfail","Inala","Ipswich","Isle Of Capri","Jacobs Well","Jimboomba","Jindalee","Kelvin Grove","Kenmore",
    "Kenmore Hills","Keperra","Kepnock","Kingston","Kirwan","Kuluin","Kuraby","Labrador","Lawnton","Loganlea",
    "Logan Central","Loganholme","Long Pocket","Longreach","Lota","Lutwche","MacGregor","Mackay","Macgregor","Manly",
    "Manly West","Mansfield","Marcus Beach","Maroochydore","Margate","Maudsland","McDowall","Mermaid Beach","Mermaid Waters",
    "Miami","Middle Park","Milton","Mitchelton","Moffat Beach","Molendinar","Mooloolaba","Mooloola","Moranbah","Morayfield",
    "Morningside","Mount Cotton","Mount Gravatt","Mount Gravatt East","Mount Isa","Mount Ommaney","Mount Pleasant","Mountain Creek",
    "Mudgeeraba","Murarrie","Murrumba Downs","Nambour","Narangba","Nathan","Nerang","Newmarket","New Farm","Newstead",
    "Nundah","Noosa","Noosa Heads","Noosaville","Norman Park","North Mackay","North Rockhampton","Northgate","Nudgee","Nudgee Beach",
    "Ooralea","Oxenford","Oxley","Pacific Pines","Paddington","Palm Beach","Palmview","Parkwood","Parkinson","Paget",
    "Pelican Waters","Petrie","Pialba","Pimlico","Pimpama","Pinkenba","Point Lookout","Pomona","Port Douglas","Proserpine",
    "Rainbow Beach","Rangeville","Rasmussen","Raceview","Redland Bay","Redbank","Redbank Plains","Red Hill","Richlands",
    "Robertson","Robina","Rochedale","Rochedale South","Rockhampton","Rockville","Rollingstone","Runcorn","Rural View","Ruse",
    "Sadliers Crossing","Salisbury","Sanctuary Cove","Sandgate","Scarborough","Shailer Park","Shelly Beach","Silkstone","Sippy Downs",
    "Slacks Creek","Smithfield","South Brisbane","South Mackay","South Toowoomba","Southport","Spring Hill","Springfield","Springfield Lakes",
    "Springwood","Stafford","Stafford Heights","Stretton","Strathpine","Stuart","Sunnybank","Sunnybank Hills","Surfers Paradise","Tanah Merah",
    "Taringa","Tarragindi","Teneriffe","The Gap","Thuringowa Central","Tewantin","Tingalpa","Toombul","Toowong","Toowoomba",
    "Townsville","Tuggeranong","Tugun","Upper Coomera","Upper Mount Gravatt","Urraween","Varsity Lakes","Victoria Point","Virginia","Wakerley",
    "Wavell Heights","Wellington Point","West End","West Mackay","Westcourt","Whitsunday","Willow Vale","Windsor","Wishart","Wongawallan",
    "Woodridge","Worongary","Wynnum","Wynnum West","Yarrabilba","Yatala","Yeerongpilly","Yeronga","Zillmere","Boondall",
    "Caboolture","Beachmere","Bellmere","Beerburrum","Beerwah","Caloundra","Clontarf","Donnybrook","Elimbah","Godwin Beach",
    "Landsborough","Mango Hill","Morayfield","Ningi","Toorbul","Wamuran","Woodford","Narangba","Dayboro","Mount Mee",
    "Kurwongbah","Wamuran","Bongaree","Welsby","Ningi","Banksia Beach","White Patch","Bellara","Rothwell","Kippa-Ring",
    "Redcliffe","Scarborough","Newport","Margate","Clontarf","Woody Point","Deception Bay","Burpengary","Morayfield","Caboolture",
    "Toowoomba","Newtown","South Toowoomba","East Toowoomba","Rangeville","Harlaxton","Darling Heights","Harristown","Wilsonton","Glenvale",
    "Rockville","Westbrook","Highfields","Gowrie Junction","Pittsworth","Clifton","Warwick","Stanthorpe","Girraween",
    "Innisfail","Atherton","Mareeba","Kuranda","Mossman","Port Douglas","Daintree","Cooktown","Weipa","Cairns",
    "Cairns City","Cairns North","Edge Hill","Whitfield","Smithfield","Redlynch","Gordonvale","Edmonton","Woree","Earlville",
    "Bungalow","Manunda","Manoora","Mooroobool","Westcourt","Bayview Heights","Whitfield","Trinity Beach","Palm Cove","Clifton Beach",
    "Townsville","Thuringowa","Kirwan","Aitkenvale","Cranbrook","Garbutt","Hyde Park","Hermit Park","North Ward","Railway Estate",
    "Rowes Bay","Belgian Gardens","Mysterton","Pimlico","Rosslea","South Townsville","Stuart","Bohle","Bohle Plains","Shaw",
    "Condon","Kelso","Burdell","Deeragun","Jensen","Rasmussen","Bohle Plains","Mount Louisa","Roseneath","Townsville City",
    "Mackay","North Mackay","South Mackay","East Mackay","Rural View","Ooralea","Paget","Beaconsfield","Mount Pleasant","Andergrove",
    "Farleigh","Eimeo","Blacks Beach","Shoal Point","Bucasia","Bakers Creek","Slade Point","Hay Point","Sarina",
    "Rockhampton","Frenchville","Park Avenue","Norman Gardens","Kawana","Berserker","Allenstown","Gracemere","Yeppoon","Emu Park",
    "Gladstone","Barney Point","Clinton","Callemondah","Toolooa","Boyne Island","Tannum Sands","Miriam Vale","Agnes Water",
    "Bundaberg","Avenell Heights","Avoca","Kepnock","Svensson Heights","Walkervale","Norville","Kensington","Thabeban",
    "Maryborough","Hervey Bay","Torquay","Scarness","Pialba","Urraween","Eli Waters","Dundowran","Point Vernon","Craignish",
  ],

  WA: [
    "Abbeydale","Admiralty","Alcoa","Alexander Heights","Alfred Cove","Alkimos","Armadale","Armadale","Ashby","Ashfield",
    "Attadale","Atwell","Aubin Grove","Aveley","Balcatta","Baldivis","Balga","Ballajura","Banksia Grove","Bassendean",
    "Bayswater","Beaconsfield","Beckenham","Bedfordale","Beechboro","Beldon","Bellevue","Belmont","Bertram","Bibra Lake",
    "Bicton","Boya","Brabham","Broadwater","Brookdale","Broome","Burswood","Butler","Cable Beach","Calista",
    "Camillo","Canning Vale","Cannington","Carabooda","Cardup","Carlisle","Carmel","Caversham","Champion Lakes","Churchlands",
    "City Beach","Claremont","Clarkson","Cloverdale","Cockburn Central","Contiguous","Coogee","Coolbinia","Coolbellup","Cottesloe",
    "Currambine","Dalkeith","Darlington","Dayton","Dianella","Duncraig","Dunreath","East Cannington","East Fremantle","East Perth",
    "East Rockingham","East Victoria Park","Eden Hill","Edgewater","Eglinton","Ellenbrook","Erskine","Esperance","Falcon","Ferndale",
    "Fitzroy Crossing","Floreat","Forrestdale","Forrestfield","Fremantle","Girrawheen","Glen Forrest","Glendalough","Gosnells","Greenfield",
    "Greenwood","Gwelup","Halls Head","Halls Creek","Hammond Park","Harrisdale","Helena Valley","Henderson","Henley Brook","Herne Hill",
    "High Wycombe","Highgate","Hilbert","Hillarys","Hillman","Hilton","Hope Valley","Huntingdale","Inglewood","Innaloo",
    "Jandakot","Joondalup","Joondanna","Kalamunda","Kallaroo","Kardinya","Karawara","Karratha","Karrinyup","Kelmscott",
    "Kenwick","Kewdale","Kiara","Kingsley","Kinross","Kojonup","Koondoola","Kununurra","Lake Coogee","Lakeside",
    "Langford","Landsdale","Leederville","Leeming","Lesmurdie","Lockridge","Lynwood","Madeley","Maddington","Maida Vale",
    "Mandurah","Marangaroo","Margaret River","Martin","Maylands","Medina","Merriwa","Mindarie","Middle Swan","Midvale",
    "Midland","Mirrabooka","Mosman Park","Mount Hawthorn","Mount Helena","Mount Lawley","Mount Pleasant","Mundaring","Munster","Murdoch",
    "Myaree","Naval Base","Newman","Nollamara","Noranda","North Beach","North Coogee","North Fremantle","North Perth","Northbridge",
    "Ocean Reef","O'Connor","Osborne Park","Palmyra","Parkwood","Peppermint Grove","Perth","Piara Waters","Pickering Brook","Port Hedland",
    "Queens Park","Quinns Rocks","Redcliffe","Ridgewood","Riverton","Rivervale","Roebuck","Rockingham","Rossmoyne","Safety Bay",
    "Salter Point","Samson","Scarborough","Secret Harbour","Serpentine","Shelley","Shoalwater","Singleton","Sorrento","South Coogee",
    "South Fremantle","South Guildford","South Hedland","South Lake","South Perth","Spearwood","Stirling","Subiaco","Success","Swan View",
    "Swanbourne","Thornlie","Trigg","Tuart Hill","Two Rocks","Upper Swan","Viveash","Waikiki","Wandi","Wangara",
    "Wannanup","Wanneroo","Warwick","Wattle Grove","Welshpool","Wembley","Wembley Downs","Westminster","White Gum Valley","Willagee",
    "Willbridge","Willeton","Winthrop","Woodbridge","Woodlands","Woodvale","Wooroloo","Yokine","Yanchep","Yangebup",
    "Fremantle","Victoria Park","Carlisle","Lathlain","Rivervale","Ascot","Perth Airport","Belmont","Cloverdale","Redcliffe",
    "Kewdale","Welshpool","Queens Park","Cannington","Beckenham","Langford","Maddington","Kenwick","Thornlie","Southern River",
    "Forrestdale","Harrisdale","Piara Waters","Canning Vale","Willetton","Riverton","Rossmoyne","Shelley","Ferndale","Parkwood",
    "Manning","Como","South Perth","St James","Bentley","Karawara","Waterford","Salter Point","Curtin","Brentwood",
    "Leeming","Murdoch","Kardinya","Samson","North Lake","Bibra Lake","South Lake","Spearwood","Coolbellup","Hamilton Hill",
    "Coogee","Munster","Henderson","Wandi","Wellard","Kwinana","Calista","Medina","Orelia","Parmelia",
    "Leda","Baldivis","Rockingham","Safety Bay","Waikiki","Shoalwater","Hillman","Peron","Cooloongup","Belmont",
    "Geraldton","Dongara","Northampton","Kalbarri","Carnarvon","Exmouth","Karratha","Dampier","Tom Price","Newman",
    "Port Hedland","South Hedland","Broome","Derby","Kununurra","Wyndham","Halls Creek","Warmun","Fitzroy Crossing",
    "Laverton","Leonora","Kalgoorlie","Boulder","Kambalda","Coolgardie","Norseman","Esperance","Ravensthorpe","Hopetoun",
    "Albany","Denmark","Mount Barker","Manjimup","Pemberton","Northcliffe","Walpole","Bunbury","Eaton","Australind",
    "Leschenault","Harvey","Collie","Busselton","Dunsborough","Margaret River","Augusta","Vasse","Yallingup","Eagle Bay",
  ],

  SA: [
    "Aberfoyle Park","Aboyne","Acacia Hills","Acres","Adare","Adelaide","Adeliede","Alberton","Allenby Gardens","Altona",
    "Andrews Farm","Angle Park","Angle Vale","Ascot Park","Ashford","Athelstone","Balaklava","Banksia Park","Belair","Berri",
    "Beverley","Bibaringa","Birdwood","Blair Athol","Blakeview","Bolivar","Bowden","Brahma Lodge","Brighton","Broadview",
    "Brompton","Brooklyn Park","Burnside","Campbelltown","Camden Park","Cavan","Christie Downs","Christies Beach","Clearview","Coromandel Valley",
    "Crafers","Craigburn Farm","Craigmore","Croydon","Darlington","Davoren Park","Daw Park","Dulwich","Edwardstown","Elizabeth",
    "Elizabeth Downs","Elizabeth East","Elizabeth Grove","Elizabeth North","Elizabeth Park","Elizabeth South","Elizabeth Vale","Enfield","Evandale","Evanston",
    "Evanston Park","Evanston South","Fairview Park","Ferryden Park","Firle","Flinders Park","Flagstaff Hill","Forestville","Fulham","Fulham Gardens",
    "Fullarton","Gawler","Gawler Belt","Gawler East","Gawler South","Gepps Cross","Gillman","Gilles Plains","Glanville","Glen Osmond",
    "Glenelg","Glenelg East","Glenelg North","Glenelg South","Glenside","Globe Derby Park","Glynde","Goodwood","Grange","Greenacre",
    "Greenways","Greenwith","Gumeracha","Hackham","Hackham West","Hackney","Hahndorf","Hallett Cove","Hampstead Gardens","Hayborough",
    "Hazelwood Park","Hectorville","Hewett","Highbury","Highgate","Hillbank","Hillcrest","Hilton","Holden Hill","Hope Valley",
    "Hove","Ingle Farm","Inner Harbor","Joslin","Kadina","Kangaroo Island","Kapunda","Kensington","Kensington Gardens","Kensington Park",
    "Keysborough","Kidman Park","Kilburn","Kilkenny","Kingston Park","Kirkcaldy","Largs Bay","Largs North","Linden Park","Lightsview",
    "Lockleys","Lonsdale","Lower Mitcham","Loxton","Marden","Marion","Marryatville","Maslin Beach","Mawson Lakes","Maylands",
    "Mayfair","McLaren Vale","Medindie","Medindie Gardens","Millswood","Mitcham","Mitchell Park","Modbury","Modbury Heights","Modbury North",
    "Moana","Morphett Vale","Morphettville","Mount Barker","Mount Gambier","Murray Bridge","Nailsworth","Newton","Noarlunga","Noarlunga Centre",
    "Norwood","North Adelaide","North Haven","North Plympton","Northfield","Northgate","O'Halloran Hill","Oak Valley","Oaklands Park","Old Reynella",
    "One Tree Hill","Para Hills","Para Hills West","Para Vista","Parafield","Parafield Gardens","Paralowie","Park Holme","Payneham","Payneham South",
    "Pennington","Peterhead","Plympton","Plympton Park","Port Adelaide","Port Noarlunga","Port Noarlunga South","Port Augusta","Port Pirie","Port Lincoln",
    "Prospect","Ramsgate","Redwood Park","Renmark","Reynella","Reynella East","Richmond","Ridgehaven","Riverton","Riverside",
    "Rose Park","Rosewater","Rostrevor","Royal Park","Salisbury","Salisbury Downs","Salisbury East","Salisbury Heights","Salisbury North","Salisbury Park",
    "Salisbury Plain","Seaford","Seaford Meadows","Seaford Rise","Seacombe Gardens","Seacombe Heights","Semaphore","Semaphore Park","Semaphore South","Sefton Park",
    "Sellicks Beach","Skye","Smithfield","Smithfield Plains","Somerton Park","South Plympton","Southgate","Stepney","Stirling","Stonyfell",
    "St Agnes","St Georges","St Marys","St Peters","Summertown","Surrey Downs","Tea Tree Gully","Tennyson","Thebarton","Thorngate",
    "Torrensville","Tranmere","Trott Park","Toorak Gardens","Unley","Unley Park","Valley View","Walkerville","Wayville","West Beach",
    "West Croydon","West Hindmarsh","West Lakes","West Lakes Shore","West Thebarton","West Torrens","Whyalla","Willaston","Windsor Gardens","Wingfield",
    "Woodcroft","Woodville","Woodville Gardens","Woodville North","Woodville Park","Woodville West","Wynn Vale","Ingle Farm","Hillbank","Salisbury",
    "Aldinga","Aldinga Beach","Sellicks Hill","McLaren Flat","Willunga","Victor Harbor","Port Elliot","Goolwa","Goolwa North","Currency Creek",
    "Hindmarsh Island","Milang","Strathalbyn","Sandergrove","Callington","Sandergrove","Murray Bridge","Monarto","Tailem Bend","Meningie",
    "Wellington","Mannum","Walker Flat","Bow Bridge","Swan Reach","Waikerie","Loxton","Berri","Barmera","Renmark",
    "Clare","Kapunda","Gawler","Barossa Valley","Nuriootpa","Tanunda","Angaston","Eden Valley","Mount Pleasant","Springton",
    "Williamstown","Lyndoch","Rowland Flat","Greenock","Seppeltsfield","Marananga","Dorrien","Bethany","Moculta","Keyneton",
    "Eudunda","Truro","Sandergrove","Sedan","Cambrai","Mannum","Birdwood","Gumeracha","Lobethal","Woodside","Mount Barker",
    "Hahndorf","Verdun","Bridgewater","Aldgate","Stirling","Crafers","Piccadilly","Summertown","Uraidla","Basket Range",
    "Magill","Teringie","Norton Summit","Cherryville","Marble Hill","Leawood Gardens","Athelstone","Burnside","Auldana","Paradise",
    "Rostrevor","Newton","Campbelltown","Magill","Kensington","Norwood","St Peters","Hackney","College Park","Payneham",
    "Evandale","Medindie","Walkerville","Gilberton","Tranmere","Felixstow","Glynde","Firle","Kensington Gardens","Rose Park",
    "Dulwich","Unley","Malvern","Goodwood","Millswood","Clarence Park","Colonel Light Gardens","Panorama","Lynton","Belair",
    "Coromandel Valley","Blackwood","Hawthorndene","Craigburn Farm","Mitchell Park","Morphett Vale","Hackham West","Christie Downs","Woodcroft","Flagstaff Hill",
    "Aberfoyle Park","Hallett Cove","Trott Park","Happy Valley","O'Halloran Hill","Chandlers Hill","Darlington","Seacombe Heights","Seacombe Gardens",
    "Marion","Park Holme","Oaklands Park","Sturt","Morphettville","Camden Park","Glengowrie","Glandore","South Plympton","Plympton",
    "Plympton Park","Netley","Cowandilla","West Hindmarsh","Hilton","Keswick","Richmond","Thebarton","Torrensville","Mile End",
    "Brooklyn Park","Lockleys","Fulham","Fulham Gardens","West Beach","Grange","Seaton","Henley Beach","Henley Beach South","Grange",
    "Tennyson","Semaphore","Semaphore Park","Exeter","Pennington","Mansfield Park","Angle Park","Kilburn","Nailsworth","Prospect",
    "Blair Athol","Clearview","Enfield","Northfield","Valley View","Greenacres","Para Hills","Para Hills West","Para Vista","Holden Hill",
    "Modbury","Modbury Heights","Modbury North","Tea Tree Gully","Fairview Park","Gilles Plains","Hope Valley","Banksia Park","Surrey Downs","Highbury",
    "Dernancourt","Golden Grove","Greenwith","One Tree Hill","Gawler","Evanston","Evanston Park","Evanston South","Evanston Gardens","Hillbank",
    "Two Wells","Virginia","Waterloo Corner","Angle Vale","Hewett","Concordia","Roseworthy","Hamley Bridge","Kapunda","Freeling",
  ],

  TAS: [
    "Acton Park","Austins Ferry","Bagdad","Battery Point","Beaconsfield","Berriedale","Bicheno","Blackmans Bay","Bridgewater","Brighton",
    "Bruny Island","Burnie","Cambridge","Campbell Town","Campania","Carrick","Chigwell","Claremont","Clarence","Clarendon Vale",
    "Clentamara","Copping","Cygnet","Derwent Park","Devonport","Dodges Ferry","Dunalley","Dynnyrne","East Devonport","East Launceston",
    "Ellendale","Evandale","Exeter","Fern Tree","Geeveston","Glenorchy","Glebe","Glenview","Granton","Hamilton",
    "Herdsmans Cove","Hobart","Howrah","Huonville","Inveresk","Invermay","Karoola","Kettering","Kingston","Kingston Beach",
    "Launceston","Lauderdale","Lenah Valley","Lindisfarne","Longford","Lutana","Margate","Mayfield","Mole Creek","Montagu Bay",
    "Moonah","Mornington","Mount Nelson","Mount Stuart","Mowbray","New Norfolk","New Town","Newnham","Norwood","Oatlands",
    "Old Beach","Oakdowns","Orielton","Perth","Pontville","Prospect Vale","Queenstown","Ravenswood","Richmond","Risdon",
    "Risdon Vale","Riverside","Rokeby","Rosny","Rosny Park","Rowella","Sandy Bay","Scottsdale","Seven Mile Beach","Shorewell Park",
    "Smithton","Snug","Sorell","South Hobart","South Launceston","Spreyton","St Helens","Swansea","Taroona","Tolmans Hill",
    "Tranmere","Trevallyn","Ulverstone","Warrane","Westbury","West Hobart","West Launceston","Waratah","Wivenhoe","Wynyard",
    "Youngtown","Zeehan","Penguin","Deloraine","Sheffield","Railton","Latrobe","Sassafras","Roland","Gowrie Park","Claude Road",
    "Cethana","Barrington","Kimberley","Forth","Turners Beach","Ulverstone","Penguin","Sulphur Creek","Riana","Leith",
    "Devonport","East Devonport","Spreyton","Latrobe","Port Sorell","Shearwater","Flowerdale","Wesley Vale","Tarleton","Moriarty",
    "Glengarry","Frankford","Selbourne","Hagley","Carrick","Westbury","Longford","Perth","Evandale","Campbell Town",
    "Ross","Oatlands","Bothwell","Hamilton","Wayatinah","Tarraleah","Miena","Bronte Park","Derwent Bridge","Queenstown",
    "Strahan","Zeehan","Rosebery","Tullah","Burnie","Somerset","Wynyard","Boat Harbour","Stanley","Smithton",
    "Forest","Marrawah","Arthur River","Bridport","George Town","Beaconsfield","Exeter","Beauty Point","Kayena","Bell Bay",
    "Low Head","St Marys","Fingal","Avoca","Bicheno","Swansea","Orford","Triabunna","Rheban","Raspins Beach",
    "Dunalley","Dodges Ferry","Carlton","Primrose Sands","Copping","Bream Creek","Boomer Bay","Forcett","Pawleena","Sorell",
    "Midway Point","Cambridge","Seven Mile Beach","Roches Beach","South Arm","Cremorne","Rokeby","Lauderdale","Howrah","Geilston Bay",
    "Clarendon Vale","Mornington","Warrane","Montagu Bay","Rosny Park","Rosny","Bellerive","Howrah","Tranmere","Lindisfarne",
    "Glenorchy","Lutana","Derwent Park","Berriedale","Claremont","Austins Ferry","Granton","Bridgewater","Brighton","Pontville",
    "Bagdad","Campania","Colebrook","Dysart","Richmond","Tea Tree","Runnymede","Rokeby","Pittwater","Orford","Buckland",
    "Triabunna","Swansea","Dolphin Sands","Coles Bay","Bicheno","Scamander","Beaumaris","St Helens","Pyengana","Herrick",
    "Scottsdale","Bridport","Lebrina","Pipers Brook","Lilydale","Rocherlea","Newnham","Punchbowl","Ravenswood","Mowbray","Norwood",
    "Youngtown","Kings Meadows","Norwood","Prospect","St Leonards","Waverley","Summerhill","East Launceston","Trevallyn","Riverside",
    "Legana","Grindelwald","Legana","West Tamar","Exeter","Gravelly Beach","Sidmouth","Greens Beach","Beaconsfield","Deviot",
    "Beauty Point","Kelso","George Town","Low Head","Hillwood","Dilston","Lilydale","Golconda","Lebrina","Bangor",
    "Winnaleah","Ringarooma","Legerwood","Scottsdale","Bridport","Pipers River","Pipers Brook","Rowella","Kayena","Bay of Fires",
    "Gladstone","Petal","Pioneer","Nook","Turners Beach","Forth","Lactos","Preolenna","Hampshire","Natone","West Ridgley",
    "Ridgley","Mooreville","Havenview","Montello","Upper Burnie","Wivenhoe","Acton","Parklands","Park Grove","Hillcrest",
    "Romaine","Cooee","Cam","South Burnie","Shorewell Park","Lorn","Emu Heights","Cam","Wilmot","Henrietta","Kindred",
    "Burnie","West Ulverstone","Ulverstone","Sulphur Creek","Riana","Leith","Penguin","Boat Harbour Beach","Boat Harbour","Rocky Cape",
    "Sisters Creek","Wynyard","Table Cape","Fossil Bluff","Yolla","Upper Castra","Castra","Springfield","Lorinna","Mole Creek","Mersey Forest",
    "Deloraine","Westbury","Longford","Perth","Evandale","Campbell Town","Ross","Oatlands","Colebrook","Brighton","Bridgewater","New Norfolk",
  ],

  ACT: [
    "Acton","Ainslie","Amaroo","Aranda","Banks","Barton","Belconnen","Bonner","Bonython","Braddon",
    "Bruce","Calwell","Campbell","Casey","Chapman","Charnwood","Chifley","Chisholm","Civic","Conder",
    "Cook","Coombs","Crace","Curtin","Deakin","Dickson","Downer","Duffy","Dunlop","Evatt",
    "Fadden","Fisher","Florey","Flynn","Forde","Forrest","Franklin","Fraser","Fyshwick","Garran",
    "Gilmore","Gordon","Gowrie","Greenway","Griffith","Gungahlin","Hall","Harrison","Hawker","Higgins",
    "Holder","Holt","Hughes","Hume","Hackett","Isabella Plains","Jacka","Jerrabomberra","Kaleen","Kambah",
    "Kenny","Kingston","Latham","Lawson","Lyneham","Lyons","Macarthur","Macgregor","Macquarie","Majura",
    "McKellar","Melba","Mitchell","Molonglo","Moncrieff","Monash","Mount Mugga Mugga","Narrabundah","Nicholls","Ngunnawal",
    "O'Connor","O'Malley","Oxley","Page","Palmerston","Phillip","Pialligo","Red Hill","Reid","Richardson",
    "Rivett","Russell","Scullin","Spence","Stirling","Stromlo","Symonston","Taylor","Theodore","Throsby",
    "Torrens","Tuggeranong","Turner","Uriarra Village","Waramanga","Watson","Weetangera","Weston","Whitlam","Wright",
    "Yarralumla","Yass","Googong","Queanbeyan",
  ],

  NT: [
    "Acacia Hills","Adelaide River","Alawa","Alice Springs","Alyangula","Anula","Araluen","Bakewell","Batchelor","Bayview",
    "Berry Springs","Borroloola","Braitling","Brinkin","Cable Beach","Casuarina","Ciccone","Coconut Grove","Coolalinga","Cullen Bay",
    "Darwin","Darwin City","Darwin Waterfront","Daly Waters","Desert Springs","Driver","Durack","East Side","Elliott","Emungalan",
    "Fannie Bay","Farrar","Flynn","Gapuwiyak","Gillen","Girraween","Gray","Gunn","Holtze","Howard Springs",
    "Humpty Doo","Jabiru","Johnston","Karama","Katherine","Katherine East","Keep River","Lakeview","Larrakeyah","Larapinta",
    "Leanyer","Livingstone","Lyons","Malak","Maningrida","Marlow Lagoon","Mataranka","Millner","Mindil Beach","Mitchell",
    "Moil","Moulden","Muirhead","Nakara","Nhulunbuy","Nightcliff","Noonamah","Palmerston","Parap","Pine Creek",
    "Rapid Creek","Renner Springs","Rosebery","Roebuck","Ross","Sadadeen","Stuart","Stuart Park","Tennant Creek","Tindal",
    "Tiwi","Virginia","Wagaman","Wanguri","Woolner","Woodroffe","Wulagi","Yarrawonga","Yarraville",
    "Jingili","Lyons","Moil","Wagaman","Wulagi","Tiwi","Alawa","Nakara","Leanyer","Wanguri","Muirhead",
    "Brinkin","Coconut Grove","Nightcliff","Rapid Creek","Casuarina","Anula","Wulagi","Malak","Karama","Lakeview",
    "Gunn","Palmerston","Rosebery","Durack","Moulden","Farrar","Bakewell","Woodroffe","Johnston","Gray","Driver","Marlow Lagoon",
    "Yarrawonga","Coolalinga","Virginia","Noonamah","Humpty Doo","Acacia Hills","Berry Springs","Girraween","Howard Springs",
    "Freds Pass","Livingstone","Darwin River","Batchelor","Adelaide River","Pine Creek","Hayes Creek","Katherine","Emungalan","Tindal",
    "Mataranka","Larrimah","Daly Waters","Elliott","Renner Springs","Tennant Creek","Ali Curung","Wauchope","Newcastle Waters","Dunmarra",
    "Nhulunbuy","Alyangula","Jabiru","Gunbalanya","Maningrida","Ramingining","Ngukurr","Borroloola","Cape Crawford","Robinson River","Timber Creek",
    "Alice Springs","Larapinta","Gillen","Sadadeen","Stuart","Ross","Desert Springs","Araluen","Flynn","Braitling","Ciccone",
    "Holtze","East Side","Ilparpa","Greatorex","Stirling","Irlpme","Chifley","The Gap","Gapuwiyak","Alpurrurulam",
    "Harts Range","Aileron","Barrow Creek","Ti Tree","Yuendumu","Mount Allan","Ltyentye Apurte","Loves Creek","Laramba",
    "Willowra","Nyrripi","Yuendumu","Mount Liebig","Papunya","Haasts Bluff","Hermannsburg","Finke","Simpson","Kulgera",
    "Mutitjulu","Yulara","Curtin Springs","Erldunda","Maryvale","Titjikala","Santa Teresa","Harts Range","Ammaroo","Alpurrurulam",
  ],
};