import { useState, useEffect } from "react";
import SEOHead from "../components/SEOHead";
import EstimateLoader from "../components/EstimateLoader";
import { Link, useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { ArrowLeft, Car, DollarSign, MapPin, MessageCircle, Globe, TrendingUp, TrendingDown, Minus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import QuoteRequestModal from "../components/QuoteRequestModal";
import CommunityInsight from "../components/CommunityInsight";
import PriceBreakdown from "../components/PriceBreakdown";
import { toast } from "sonner";

export default function EstimateResult() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showQuoteModal, setShowQuoteModal] = useState(false);
  const [posting, setPosting] = useState(false);
  const [posted, setPosted] = useState(false);
  const navigate = useNavigate();

  const urlParams = new URLSearchParams(window.location.search);
  const id = urlParams.get("id");

  useEffect(() => {
    if (!id) return;
    const load = async () => {
      const results = await base44.entities.QuoteCheck.filter({ id });
      if (results.length > 0) setData(results[0]);
      setLoading(false);
    };
    load();
  }, [id]);

  const handlePostPublicly = async () => {
    setPosting(true);
    try {
      await base44.functions.invoke("broadcastMechanicLeads", { ...data, id: data.id });
      setPosted(true);
      toast.success("Sent to local mechanics!");
    } catch {
      toast.error("Failed to send. Please try again.");
    } finally {
      setPosting(false);
    }
  };

  if (loading) {
    return <EstimateLoader />;
  }

  if (!data) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-20 text-center">
        <p className="text-muted-foreground">Result not found.</p>
        <Link to="/"><Button className="mt-4">Check a new quote</Button></Link>
      </div>
    );
  }

  const low = data.price_low;
  const high = data.price_high;
  const avg = data.price_average;

  // Position indicator (0–100%) for the range bar
  const rangeWidth = high - low;

  return (
    <div className="w-full py-8 sm:py-12">
      <SEOHead
        title="Service Estimate | ServCheck"
        description="Your service cost estimate results."
        path="/estimate-result"
        noindex={true}
      />
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between mb-8"
      >
        <Link to="/" className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" />
          New check
        </Link>
      </motion.div>

      {/* Car info */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="rounded-2xl bg-gradient-to-br from-[#1a237e] to-[#1565c0] p-4 mb-6 flex items-center gap-3"
      >
        <div className="h-11 w-11 rounded-xl bg-white/20 flex items-center justify-center flex-shrink-0">
          <Car className="h-5 w-5 text-white" />
        </div>
        <div className="min-w-0">
          <p className="font-heading font-bold text-white leading-tight">
            {data.car_year} {data.car_make} {data.car_model}
          </p>
          <p className="text-blue-200 text-xs mt-0.5 truncate">
            {data.service_type} · {data.suburb ? `${data.suburb}, ` : ""}{data.state}
          </p>
        </div>
      </motion.div>

      <div className="space-y-6">

        {/* Transparency banner */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-2xl bg-blue-50 border border-blue-200 px-4 py-3 flex items-start gap-3"
        >
          <span className="text-blue-500 text-base mt-0.5 flex-shrink-0">ℹ️</span>
          <p className="text-xs text-blue-800 leading-relaxed">
            <strong>This is a market estimate, not a binding quote.</strong> These figures are generated by AI from real Australian pricing data. Your actual cost may vary based on your vehicle's specific condition, parts availability, and location. Always get a written quote from a licensed mechanic before authorising any work.
          </p>
        </motion.div>

        {/* Market Estimate Card */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 }}
          className="rounded-2xl border-2 border-emerald-400 bg-gradient-to-br from-emerald-50 to-white p-6"
        >
          <div className="flex items-center gap-2 mb-4">
            <DollarSign className="h-5 w-5 text-emerald-600" />
            <p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Australian Market Estimate</p>
          </div>

          {/* Big range display */}
          <div className="text-center mb-6">
            <p className="text-4xl font-heading font-black text-[#1a237e]">
              ${low?.toLocaleString()} – ${high?.toLocaleString()}
            </p>
            <p className="text-sm text-slate-500 mt-1">Typical price range in {data.state}</p>
          </div>

          {/* Visual range bar */}
          <div className="mb-5">
            <div className="relative h-4 bg-slate-100 rounded-full overflow-hidden">
              <div
                className="absolute top-0 bottom-0 bg-gradient-to-r from-emerald-400 to-emerald-600 rounded-full"
                style={{ left: "10%", right: "10%" }}
              />
              {/* Average marker */}
              <div
                className="absolute top-0 bottom-0 w-1 bg-[#1a237e] rounded-full"
                style={{ left: `${rangeWidth > 0 ? 10 + ((avg - low) / rangeWidth) * 80 : 50}%` }}
              />
            </div>
            <div className="flex justify-between text-[10px] font-bold text-slate-400 mt-1.5">
              <span className="flex items-center gap-0.5"><TrendingDown className="h-3 w-3" /> Low</span>
              <span className="flex items-center gap-0.5"><Minus className="h-3 w-3 text-[#1a237e]" /> Avg ${avg?.toLocaleString()}</span>
              <span className="flex items-center gap-0.5">High <TrendingUp className="h-3 w-3" /></span>
            </div>
          </div>

          {/* Three columns */}
          <div className="grid grid-cols-3 gap-2">
            <div className="rounded-xl bg-emerald-100 text-center p-3">
              <p className="text-[10px] font-bold uppercase text-emerald-700 mb-0.5">Budget</p>
              <p className="font-heading font-black text-emerald-800 text-lg">${low?.toLocaleString()}</p>
              <p className="text-[10px] text-emerald-600">Indie mechanic</p>
            </div>
            <div className="rounded-xl bg-[#1a237e] text-center p-3">
              <p className="text-[10px] font-bold uppercase text-blue-200 mb-0.5">Average</p>
              <p className="font-heading font-black text-white text-lg">${avg?.toLocaleString()}</p>
              <p className="text-[10px] text-blue-300">Market rate</p>
            </div>
            <div className="rounded-xl bg-slate-100 text-center p-3">
              <p className="text-[10px] font-bold uppercase text-slate-500 mb-0.5">Premium</p>
              <p className="font-heading font-black text-slate-700 text-lg">${high?.toLocaleString()}</p>
              <p className="text-[10px] text-slate-400">Dealership</p>
            </div>
          </div>
        </motion.div>

        {/* Summary */}
        {data.summary && (
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="rounded-2xl border border-border bg-card p-5"
          >
            <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-2">What to expect</p>
            <p className="text-sm leading-relaxed text-foreground">{data.summary}</p>
          </motion.div>
        )}

        {/* What's included */}
        <PriceBreakdown items={data.whats_included} />

        {/* Community insight */}
        <CommunityInsight
          serviceType={data.service_type}
          carMake={data.car_make}
          carModel={data.car_model}
          state={data.state}
          suburb={data.suburb}
        />

        {/* CTA — get real quotes */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="rounded-2xl border-2 border-accent/40 bg-accent/5 p-5"
        >
          <p className="font-heading font-bold text-sm mb-1">Ready to get quoted?</p>
          <p className="text-xs text-muted-foreground mb-3">Send to local mechanics so they compete for your job.</p>
          <p className="text-xs text-muted-foreground italic mb-3">⚠️ This feature is only available if there are ServCheck-listed mechanics in your area.</p>
          <Button
            onClick={handlePostPublicly}
            disabled={posting || posted}
            className="bg-accent text-accent-foreground hover:bg-accent/90 gap-2 w-full"
          >
            {posting ? <><span className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full animate-spin" /> Sending...</> :
             posted ? "✓ Sent to Mechanics" :
             <><Globe className="h-4 w-4" /> Send to Local Mechanics</>}
          </Button>
        </motion.div>

        {(data.suburb || data.state) && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25 }}
            className="rounded-2xl border border-accent/30 bg-accent/5 p-5 flex items-center justify-between gap-4"
          >
            <div>
              <p className="font-heading font-bold text-sm">Find mechanics nearby</p>
              <p className="text-xs text-muted-foreground mt-0.5">
                Browse the directory in {data.suburb ? `${data.suburb}, ` : ""}{data.state}
              </p>
            </div>
            <Button
              onClick={() => navigate(`/directory?suburb=${encodeURIComponent(data.suburb || "")}&state=${encodeURIComponent(data.state || "NSW")}`)}
              className="bg-accent text-accent-foreground hover:bg-accent/90 gap-2 flex-shrink-0"
            >
              <MapPin className="h-4 w-4" />
              Find Mechanics
            </Button>
          </motion.div>
        )}



        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="text-center pt-4"
        >
          <Link to="/">
            <Button variant="outline" size="lg" className="font-heading font-semibold">
              Check another quote
            </Button>
          </Link>
        </motion.div>
      </div>
    </div>
  );
}