import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import SEOHead from "@/components/SEOHead";

function H1({ children }) {
  return <h1 className="text-2xl sm:text-3xl font-heading font-black text-foreground mb-2">{children}</h1>;
}
function H2({ children }) {
  return <h2 className="text-base sm:text-lg font-heading font-bold text-foreground mt-8 mb-3 pb-2 border-b border-border">{children}</h2>;
}
function P({ children }) {
  return <p className="text-sm text-foreground leading-relaxed mb-3">{children}</p>;
}
function UL({ children }) {
  return <ul className="list-disc list-outside ml-5 space-y-1.5 mb-3 text-sm text-foreground leading-relaxed">{children}</ul>;
}
function LI({ children }) {
  return <li>{children}</li>;
}
function Strong({ children }) {
  return <strong className="font-semibold">{children}</strong>;
}
function Callout({ children }) {
  return (
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 leading-relaxed mb-4">
      {children}
    </div>
  );
}

export default function TermsOfService() {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title="Terms of Service | ServCheck Australia"
        description="ServCheck's Terms of Service — the rules for using Australia's car service transparency platform."
        path="/terms"
      />

      {/* Header */}
      <div className="border-b border-border bg-card">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 sm:py-10">
          <Link to="/" className="inline-flex items-center gap-1.5 text-muted-foreground hover:text-foreground text-sm mb-5 transition-colors">
            <ArrowLeft className="h-3.5 w-3.5" /> Back to ServCheck
          </Link>
          <H1>Terms of Service</H1>
          <p className="text-xs text-muted-foreground mt-1">Last updated: 28 June 2026</p>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">

        <P>These Terms of Service ("Terms") constitute a legally binding agreement between you and <Strong>ServCheck Pty Ltd (ACN ___ ___ ___)</Strong> ("ServCheck", "we", "us", and "our") and govern your access to and use of the ServCheck website and mobile applications (collectively, the "Service"). These Terms apply to vehicle owners and general users. Mechanics, workshops, and dealers are covered by our separate Partner Terms of Service. Our Privacy Policy applies to all users.</P>
        <P>Please read these Terms carefully before using the Service. By creating an account or using the Service in any way, you confirm that you have read, understood, and agreed to these Terms.</P>

        <H2>1. Eligibility</H2>
        <P>You must be at least 18 years of age to use the Service. By using the Service, you represent and warrant that you meet this requirement and that the information you provide is accurate and complete. If you do not agree to these Terms, you must not use the Service.</P>

        <H2>2. What ServCheck Is and Is Not</H2>
        <P>ServCheck provides analysis of mechanic quotes and used car prices, a car symptom guide, a digital vehicle logbook, service predictions, valuations and resale reports, community price information, a directory of mechanics, and a lead marketplace that connects your service requests with independent mechanics and dealers ("Partners").</P>
        <Callout>
          <Strong>ServCheck is an information and introduction platform only.</Strong> We are not a mechanic, repairer, dealer, vehicle inspector, valuer, diagnostic service, insurer, or party to any contract between you and a Partner. When you engage a Partner, your contract is with that Partner alone. The Partner is solely responsible for their workmanship, pricing, warranties, and conduct. Consumer guarantees under the Australian Consumer Law apply against the Partner, not ServCheck. A "Verified" badge on a Partner profile means we reviewed their licence documentation at the time of verification. It is not an endorsement of their quality or a guarantee of any outcome.
        </Callout>

        <H2>3. AI-Generated Content</H2>
        <P>Verdicts, fair price ranges, scores, service predictions, valuations, resale reports, and symptom reports are estimates and general information generated by automated systems using market data and the details you provide. They may be inaccurate, incomplete, or out of date.</P>
        <P>All outputs are general information only. They are not professional, mechanical, financial, or legal advice and must not be your sole basis for accepting or rejecting a quote, buying or selling a vehicle, or making any safety decision. You should always seek independent professional advice before making significant decisions.</P>

        <H2>4. Car Symptom Guide</H2>
        <P>The Car Symptom Guide allows you to select or describe symptoms and receive a report that may include possible causes, a priority and urgency indicator, an indicative repair cost range, and suggested questions to ask a mechanic. Because this feature relates to vehicle safety, the following terms apply in addition to the general terms above.</P>
        <UL>
          <LI><Strong>It is not a diagnosis.</Strong> The Car Symptom Guide does not physically inspect your vehicle and cannot diagnose it. It is not a substitute for inspection by a qualified mechanic.</LI>
          <LI><Strong>The urgency indicator is not a safety determination.</Strong> Any urgency level shown is an estimate to help you prioritise. It is not a professional assessment of roadworthiness. You must not rely on the Car Symptom Guide to decide whether your vehicle is safe to drive. If you have any doubt about your vehicle's safety, do not drive it and arrange an inspection by a qualified mechanic immediately.</LI>
          <LI><Strong>Cost ranges are indicative only.</Strong> Any repair cost figure is a general estimate and not a formal quote. The actual cost may differ substantially once a mechanic physically inspects the vehicle.</LI>
          <LI><Strong>Always seek a professional inspection.</Strong> You agree to treat any report as a prompt to seek professional inspection, not as a reason to defer or avoid one.</LI>
          <LI><Strong>Safety-critical symptoms.</Strong> If your concern involves brakes, steering, tyres, suspension, wheels, warning lights, smoke, fluid leaks, or any loss of vehicle control, treat the matter as urgent regardless of what the guide indicates and seek immediate professional inspection.</LI>
          <LI><Strong>Assumption of risk.</Strong> By using the Car Symptom Guide, you acknowledge that it provides general information only, that you will not rely on it for any safety or roadworthiness decision, and that you will have your vehicle professionally inspected before acting on any report. To the maximum extent permitted by law, you use the Car Symptom Guide at your own risk.</LI>
        </UL>

        <H2>5. Your Account</H2>
        <P>You are responsible for keeping your account credentials secure and for all activity that occurs under your account. You must not share your account with anyone else or create more than one account per person. We may suspend or permanently close accounts that breach these Terms, are involved in fraudulent activity, or are used for any unlawful purpose.</P>

        <H2>6. Credits, Subscriptions, and Payments</H2>
        <P>Certain features of the Service require credits or an active subscription. The following terms apply.</P>
        <UL>
          <LI>New accounts receive a number of introductory free credits. Additional credits are available for purchase at the prices shown at the time of purchase, in Australian dollars and inclusive of GST where applicable.</LI>
          <LI>All purchases are processed securely by Stripe. We do not store your payment card details.</LI>
          <LI>If a check fails to complete due to a fault in the Service, the credits consumed will be refunded to your account balance.</LI>
          <LI>Credits have no cash value, are non-transferable, and are not refundable for change of mind. Nothing in this clause limits any right or remedy you may have under the Australian Consumer Law.</LI>
          <LI>Premium subscriptions renew automatically at the price and billing interval shown at sign-up until you cancel. You may cancel at any time through your account settings and will retain access until the end of the billing period you have already paid for.</LI>
          <LI>Referral and bonus credits may be reversed or revoked where they were obtained through fake accounts, self-referral, or any other form of abuse.</LI>
        </UL>

        <H2>7. Upload to Earn</H2>
        <P>You may earn credits by uploading verified mechanic receipts through the logbook feature. The following terms apply to this feature.</P>
        <UL>
          <LI>A successful upload awards 2 credits. You may upload a maximum of two receipts per calendar month, for a maximum of 4 credits per month.</LI>
          <LI>Credits are awarded only after successful extraction of valid automotive service data from the uploaded receipt.</LI>
          <LI>Each receipt file may only be submitted once. Duplicate submissions will not be rewarded.</LI>
          <LI>Submitting duplicate, fabricated, or non-automotive receipts in order to earn credits is a breach of these Terms and may result in account suspension.</LI>
        </UL>

        <H2>8. Referral Program</H2>
        <P>Each user receives one personal invite code. The following terms apply to the referral program.</P>
        <UL>
          <LI>A new user may claim one referral code once at account creation. This cannot be changed after the fact.</LI>
          <LI>Each invite code may be used by a maximum of five people.</LI>
          <LI>Both the referring user and the new user receive 5 bonus credits upon a valid claim.</LI>
          <LI>Referral credits obtained through fake accounts, self-referral, or any form of manipulation will be reversed and the relevant accounts may be suspended.</LI>
        </UL>

        <H2>9. Quote Requests and Dealing With Partners</H2>
        <P>When you submit a quote, diagnostic, or symptom-related request, the details you include (such as your vehicle, the service or problem, your suburb, and any contact information you choose to provide) are shared with matching Partners so that they can respond to you. You control what contact details you share.</P>
        <P>We do not guarantee that any Partner will respond, respond within a particular timeframe, or honour any indicative price. You should inspect all work, obtain written quotes, and pay Partners directly using a payment method you trust. Your contract for any services is with the Partner, not with ServCheck.</P>

        <H2>10. Community Content and Your Responsibilities</H2>
        <P>You retain ownership of the content you submit to the Service and grant us a non-exclusive, royalty-free, worldwide licence to host, display, and use that content to operate and improve the Service. You are responsible for ensuring that anything you post is accurate, lawful, and does not infringe the rights of others.</P>
        <P>You must not submit content that is false or misleading, defamatory, abusive, discriminatory, or in breach of any law. Price submissions must reflect genuine transactions that you were personally a party to.</P>
        <P><Strong>A note on defamation.</Strong> Publicly accusing a named business of dishonesty or unlawful conduct can expose you to personal liability under Australian defamation law. Posts flagged by our automated moderation system are held for human review before being published.</P>

        <H2>11. Acceptable Use</H2>
        <P>When using the Service, you must not do any of the following:</P>
        <UL>
          <LI>Scrape, bulk download, or republish our data, directory listings, or any other content from the Service.</LI>
          <LI>Reverse engineer, decompile, or attempt to extract the source code of the Service.</LI>
          <LI>Share, sell, or transfer access to your account.</LI>
          <LI>Attempt to circumvent credits, paywalls, or moderation systems.</LI>
          <LI>Upload malware, harmful code, or unlawful content.</LI>
          <LI>Upload documents containing another person's personal information without their consent.</LI>
          <LI>Attempt to cause the Service to produce instructions for unlawful vehicle modification or tampering.</LI>
          <LI>Use any outputs from the Service to build a competing dataset, product, or service.</LI>
        </UL>

        <H2>12. Australian Consumer Law and Our Liability</H2>
        <P>Our services come with guarantees that cannot be excluded under the Australian Consumer Law. Nothing in these Terms excludes, restricts, or modifies any consumer guarantee, right, or remedy that you are entitled to under the Australian Consumer Law or any other applicable law that cannot be lawfully excluded.</P>
        <P>Subject to that, and to the maximum extent permitted by law, the following applies:</P>
        <UL>
          <LI>The Service, including all outputs and the Car Symptom Guide, is provided on an "as is" basis. We do not warrant that it will be uninterrupted, error-free, or that any output will be accurate or suitable for your purposes.</LI>
          <LI>We are not liable for the acts, omissions, workmanship, pricing, or conduct of any Partner or other user, or for any agreement you enter into with them.</LI>
          <LI>We exclude liability for indirect or consequential loss, loss of profit, and loss of data, to the extent permitted by law.</LI>
          <LI>Where our liability is not governed by a consumer guarantee, our total aggregate liability to you is limited to the greater of the amounts you paid us in the 12 months preceding the relevant event and AUD $100.</LI>
          <LI>Where our liability under a consumer guarantee cannot be excluded but may be limited, we limit our liability (at our option) to re-supplying the relevant service or paying the reasonable cost of having it re-supplied.</LI>
        </UL>

        <H2>13. Termination</H2>
        <P>You may delete your account at any time through the in-app settings. Please refer to our Privacy Policy for details of what happens to your personal information upon deletion.</P>
        <P>We may suspend or terminate your account if you commit a material breach of these Terms, engage in fraudulent conduct, or where required by law. If we terminate your account without cause on your part, we will refund the unused portion of any prepaid subscription.</P>

        <H2>14. Changes to These Terms</H2>
        <P>We may update these Terms from time to time. When we do, we will revise the "Last updated" date at the top of this page. We will notify you of material changes through the app or by email at least 14 days before they take effect. Your continued use of the Service after that date constitutes your acceptance of the updated Terms.</P>

        <H2>15. Governing Law</H2>
        <P>These Terms are governed by the laws of New South Wales, Australia. You agree to submit to the non-exclusive jurisdiction of the courts of New South Wales and the Commonwealth of Australia for any dispute arising out of or relating to these Terms or your use of the Service. If any provision of these Terms is found to be unenforceable, that provision will be severed and the remainder of these Terms will continue in full force.</P>

        {/* Footer block */}
        <div className="mt-10 pt-6 border-t border-border rounded-xl bg-muted/40 px-4 py-4 space-y-1 text-sm text-muted-foreground">
          <p className="font-semibold text-foreground text-xs uppercase tracking-widest mb-2">ServCheck Pty Ltd</p>
          <p>ACN: ___ ___ ___</p>
          <p>ABN: ___ ___ ___ ___</p>
          <p>Registered address: ____________________</p>
          <p>Contact: <a href="mailto:allenquiries@servcheck.com.au" className="text-accent underline underline-offset-2">allenquiries@servcheck.com.au</a></p>
        </div>

        <div className="mt-6 flex gap-4 text-sm">
          <Link to="/partner-terms" className="text-accent underline underline-offset-2 hover:text-accent/80">Partner Terms of Service</Link>
          <Link to="/privacy" className="text-accent underline underline-offset-2 hover:text-accent/80">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}